### ISSUE TITLE
Is there a split list of datasets?

### ISSUE THREAD

**Issue by yutaokuyama** [bioinfolabic/UTFPR-SBD3#1]
Hello. First of all, thank you for your great work.
I read in your paper that you used 10-split cross-validation to train this dataset, and kept the test data separate from it. I would like to know specifically how you divided the dataset and how many test data you used.

**Comment by bioinfolabic** [comment]
Hi @yutaokuyama, sorry for my late response.
The train and test data for each fold of the cross validation is available in the [cv_split_data.json](https://github.com/bioinfolabic/UTFPR-SBD3/blob/main/cv_split_data.json) file.
I also provided the [read_cv_split_data.py](https://github.com/bioinfolabic/UTFPR-SBD3/blob/main/read_cv_split_data.py) with a working example of how to read the data.

**Comment by yutaokuyama** [comment]
Thank you for your response. It is very helpful.
